### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory" when test could not load module

### ISSUE THREAD

**Issue by imomaliev** [asottile/detect-test-pollution#19]
Hi. Hope this helps. Thansk @cdce8p here are steps to reproduce #6 

```console
$ echo "from unknown import Unknown

def test():
    assert True" > t.py
$ echo "t.py::test" > testids
$ detect-test-pollution \
    --failing-test t.py::test \
    --testids-file testids
```

**Comment by Edward-Knight** [comment]
I've also come across this issue, reposting the stacktrace from #6 for clarity:

```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/project-Qkx4pV5j/bin/detect-test-pollution", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/virtualenvs/project-Qkx4pV5j/lib/python3.9/site-packages/detect_test_pollution.py", line 299, in main
    return _bisect(testpath, args.failing_test, testids)
  File "/root/.local/share/virtualenvs/project-Qkx4pV5j/lib/python3.9/site-packages/detect_test_pollution.py", line 224, in _bisect
    if _passed_with_testlist(testpath, failing_test, testids):
  File "/root/.local/share/virtualenvs/project-Qkx4pV5j/lib/python3.9/site-packages/detect_test_pollution.py", line 136, in _passed_with_testlist
    with open(results_json) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp4c4aahsz/results.json'
```

I've narrowed down the problem to this section of code:

https://github.com/asottile/detect-test-pollution/blob/de890cd995fe26ccd2204bc0ddca999da28cbec4/detect_test_pollution.py#L118-L130

Here we ignore a `subprocess.CalledProcessError` from running `pytest` - I assume because we expect `pytest` to return a non-zero exit code when a test fails. However, if the `pytest` command fails without running tests (e.g. when trying to import a missing module), it exits without writing anything to the `results.json` file. This ends up with us triggering the `FileNotFound` exception.

Indeed, there is a note in `_run_pytest`:

https://github.com/asottile/detect-test-pollution/blob/de890cd995fe26ccd2204bc0ddca999da28cbec4/detect_test_pollution.py#L76-L81

---

I propose instead of blanket ignoring all `CalledProcessError`, we instead only ignore exit code 1 and report a nice error message for other exit codes. Pytest document their error codes, I'll copy here to avoid linkrot: https://docs.pytest.org/en/stable/reference/exit-codes.html

> Running pytest can result in six different exit codes:
> 
> * 0: All tests were collected and passed successfully
> * 1: Tests were collected and run but some of the tests failed
> * 2: Test execution was interrupted by the user
> * 3: Internal error happened while executing tests
> * 4: pytest command line usage error
> * 5: No tests were collected
> 
> They are represented by the `pytest.ExitCode` enum. The exit codes being a part of the public API can be imported and accessed directly using: `from pytest import ExitCode`
> 
> Note: If you would like to customize the exit code in some scenarios, specially when no tests are collected, consider using the `pytest-custom_exit_code` plugin.

---

I've also now found this comment, which finds the same issue and suggests the same fix: https://github.com/asottile/detect-test-pollution/issues/6#issuecomment-1075909154 😅

As an aside, my issue specifically was running `pytest` with the positional argument of `.`(this causes pytest to try and import things it shouldn't, overriding what I have set in my `pyproject.toml`). I'm probably using the wrong arguments to `detect-test-pollution`.

Finally, thanks for the tool! After I hacked around the issue it worked great! <3

```
discovering all tests...
-> discovered 198 tests!
ensuring test passes by itself...
-> OK!
ensuring test fails with test group...
-> OK!
running step 1:
- 197 tests remaining (about 8 steps)
running step 2:
- 98 tests remaining (about 7 steps)
running step 3:
- 49 tests remaining (about 6 steps)
running step 4:
- 24 tests remaining (about 5 steps)
running step 5:
- 12 tests remaining (about 4 steps)
running step 6:
- 6 tests remaining (about 3 steps)
running step 7:
- 3 tests remaining (about 2 steps)
running step 8:
- 2 tests remaining (about 1 steps)
double checking we found it...
-> the polluting test is: <bad test>
```
